name: E2E Tests

on:
  pull_request:
  push:

env:
  TAR_PATH: heighliner.tar

jobs:
  heighliner:
    runs-on: ubuntu-latest
    steps:
      - name: Build Image
        uses: strangelove-ventures/heighliner-build-action@v0.0.3
        with:
          registry: ""
          tag: local
          tar-export-path: ${{ env.TAR_PATH }}
          platform: linux/amd64
          git-ref: ${{ github.head_ref }}

          chain: noble-fiattokenfactory-simd
          dockerfile: cosmos
          build-target: make install
          binaries: |
            - simapp/build/simd

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.TAR_PATH }}

  e2e-tests:
    needs:
      - heighliner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Load Image
        run: docker image load -i ${{ env.TAR_PATH }}

      - name: Run E2E Tests
        run: make test-e2e
