name: E2E Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Heighliner
        run: go install github.com/strangelove-ventures/heighliner@latest

      - name: Build Image
        run: make heighliner

      - name: Run E2E Tests
        run: make test-e2e
